<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MuridSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('murid')->insert([
            [
                'id_user' => 16,
                'nama' => 'Andi Saputra',
                'nis' => '1001',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-03-15',
                'no_telp' => '089876543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 17,
                'nama' => 'Budi Prakoso',
                'nis' => '1002',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-06-22',
                'no_telp' => '089765432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 18,
                'nama' => 'Cindy Amelia',
                'nis' => '1003',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-08-19',
                'no_telp' => '089654321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 19,
                'nama' => 'Deni Ramadhan',
                'nis' => '1004',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-12-01',
                'no_telp' => '089543210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 20,
                'nama' => 'Eka Putri',
                'nis' => '1005',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-09-10',
                'no_telp' => '089432109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 21,
                'nama' => 'Farhan Maulana',
                'nis' => '1006',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-01-25',
                'no_telp' => '089321098765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 22,
                'nama' => 'Gina Rahmawati',
                'nis' => '1007',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-04-17',
                'no_telp' => '089210987654',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 23,
                'nama' => 'Hendra Saputra',
                'nis' => '1008',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-05-06',
                'no_telp' => '089109876543',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 24,
                'nama' => 'Indah Permata',
                'nis' => '1009',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-11-29',
                'no_telp' => '089098765432',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 25,
                'nama' => 'Joko Santoso',
                'nis' => '1010',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-07-13',
                'no_telp' => '088987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 26,
                'nama' => 'Kevin Aditya',
                'nis' => '1011',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-10-01',
                'no_telp' => '088876543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 27,
                'nama' => 'Lilis Nuraini',
                'nis' => '1012',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-02-05',
                'no_telp' => '088765432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 28,
                'nama' => 'Miftah Huda',
                'nis' => '1013',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-12-30',
                'no_telp' => '088654321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 29,
                'nama' => 'Nia Lestari',
                'nis' => '1014',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-03-23',
                'no_telp' => '088543210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 30,
                'nama' => 'Oki Pratama',
                'nis' => '1015',
                'kelas' => 'XI RPL 1',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-06-12',
                'no_telp' => '088432109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'id_user' => 31,
                'nama' => 'Putri Ayu',
                'nis' => '1016',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-08-28',
                'no_telp' => '088321098765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 32,
                'nama' => 'Qory Amalia',
                'nis' => '1017',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-09-14',
                'no_telp' => '088210987654',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 33,
                'nama' => 'Rian Kurniawan',
                'nis' => '1018',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-07-07',
                'no_telp' => '088109876543',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 34,
                'nama' => 'Sinta Wulandari',
                'nis' => '1019',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-01-03',
                'no_telp' => '088098765432',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 35,
                'nama' => 'Tegar Wahyudi',
                'nis' => '1020',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-02-27',
                'no_telp' => '087987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 36,
                'nama' => 'Ulya Fitriana',
                'nis' => '1021',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-05-16',
                'no_telp' => '087876543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 37,
                'nama' => 'Vina Zahra',
                'nis' => '1022',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-03-05',
                'no_telp' => '087765432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 38,
                'nama' => 'Wahyu Hidayat',
                'nis' => '1023',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-10-20',
                'no_telp' => '087654321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 39,
                'nama' => 'Xena Azzahra',
                'nis' => '1024',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-06-30',
                'no_telp' => '087543210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 40,
                'nama' => 'Yoga Pratama',
                'nis' => '1025',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-04-22',
                'no_telp' => '087432109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 41,
                'nama' => 'Zahra Kusuma',
                'nis' => '1026',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-09-25',
                'no_telp' => '087321098765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 42,
                'nama' => 'Aldi Fernando',
                'nis' => '1027',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-05-31',
                'no_telp' => '087210987654',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 43,
                'nama' => 'Bella Anjani',
                'nis' => '1028',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-07-18',
                'no_telp' => '087109876543',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 44,
                'nama' => 'Candra Setiawan',
                'nis' => '1029',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-08-03',
                'no_telp' => '087098765432',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 45,
                'nama' => 'Dita Marlina',
                'nis' => '1030',
                'kelas' => 'XI RPL 2',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-10-11',
                'no_telp' => '086987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 46,
                'nama' => 'Evan Yulianto',
                'nis' => '1031',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-01-20',
                'no_telp' => '086876543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 47,
                'nama' => 'Fira Nurhaliza',
                'nis' => '1032',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-04-08',
                'no_telp' => '086765432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 48,
                'nama' => 'Galih Permadi',
                'nis' => '1033',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-06-02',
                'no_telp' => '086654321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 49,
                'nama' => 'Hilda Rosanti',
                'nis' => '1034',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-07-24',
                'no_telp' => '086543210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 50,
                'nama' => 'Irfan Maulana',
                'nis' => '1035',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-03-12',
                'no_telp' => '086432109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 51,
                'nama' => 'Jessica Andini',
                'nis' => '1036',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-08-07',
                'no_telp' => '086321098765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 52,
                'nama' => 'Kiki Susanto',
                'nis' => '1037',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-10-26',
                'no_telp' => '086210987654',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 53,
                'nama' => 'Lia Kurniasih',
                'nis' => '1038',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-05-03',
                'no_telp' => '086109876543',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 54,
                'nama' => 'Mario Anggoro',
                'nis' => '1039',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-11-14',
                'no_telp' => '086098765432',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 55,
                'nama' => 'Niken Maharani',
                'nis' => '1040',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-12-05',
                'no_telp' => '085987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 56,
                'nama' => 'Oka Wira',
                'nis' => '1041',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-09-17',
                'no_telp' => '085876543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 57,
                'nama' => 'Prita Salsabila',
                'nis' => '1042',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-04-13',
                'no_telp' => '085765432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 58,
                'nama' => 'Qasim Rahman',
                'nis' => '1043',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-07-30',
                'no_telp' => '085654321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 59,
                'nama' => 'Rani Oktaviani',
                'nis' => '1044',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'P',
                'tgl_lahir' => '2006-01-10',
                'no_telp' => '085543210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 60,
                'nama' => 'Syahrul Anam',
                'nis' => '1045',
                'kelas' => 'XI RPL 3',
                'jenis_kelamin' => 'L',
                'tgl_lahir' => '2006-02-22',
                'no_telp' => '085432109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
